;#########################################################################
;#
;# Copyright (c), 2009-2010 Synopsys, Inc. All rights reserved.
;# This file and the associated documentation are confidential 
;# and proprietary to Synopsys, Inc. 
;# 
;#
;# DISCLAIMER
;# The information contained herein is provided by Synopsys, Inc. on 
;# an "AS IS" basis without any warranty, and Synopsys has no obligation 
;# to support or otherwise maintain the information.
;#
;# Synopsys, Inc. disclaims any representation that the information 
;# does not infringe any intellectual property rights or proprietary
;# rights of any third parties. There are no other warranties given by
;# Synopsys, whether express, implied or statutory, including, without
;# limitation, implied warranties of merchantability and fitness for a
;# particular purpose.
;#
;# Synopsys, Inc. reserves the right to make changes to the information 
;# at any time and without notice.
;#
;#########################################################################
;#
;#	Change Log:
;#
;#	20 March 09 : Adding First version
;##########################################################################


;********************************
; CONTROLS
;********************************
controls(
 techParams(
 ;( parameter           value )
 ;( ----------          ----- )
  ( maskGrid       	0.005 )
  ( cadGrid        	0.005 )
  ( drcGrid        	0.005 )
  ( mfgGrid        	0.005 )
  ( scale          	1.0 )
  ( MPPS           	(list (list nil (quote cwW) 0.09 (quote cwL) 0.09 (quote cwSp) 0.10 (quote cwRowSp) 0.15 (quote Cw) "cont" (quote M1) "m1" (quote M1CwEnc) 0.005 (quote breakLayer) "psub") (list nil (quote name) "nwell" (quote pathLayer) "diff" (quote pathWidth) 0.09 (quote pathCwEnc) 0.05 (quote enclosureLayers) (list) (quote spacings) (list nil)) (list nil (quote name) "sub" (quote pathLayer) "diff" (quote pathWidth) 0.09 (quote pathCwEnc) 0.05 (quote enclosureLayers) (list) (quote spacings) (list nil)))	 )
 ) ;techParams

 techPermissions(
 ;( class               (read-only users)  (read & write users)           )
 ;( ----------          -----------------  --------------------           )
 ) ;techPermissions

 viewTypeUnits(
 ;( viewType            userUnit       dbuperuu           )
 ;( --------            --------       --------           )
  ( maskLayout     	"micron"       	1000            )
  ( schematic      	"inch"         	160             )
  ( schematicSymbol	"inch"         	160             )
  ( netlist        	"inch"         	160             ) 
 ) ;viewTypeUnits

 mfgGridResolution(
      ( 0.005000 )
 ) ;mfgGridResolution


;;;;; MPP Definitions ############################


leMPPControls (
; P type guard ring    	name    	obj-list 		spacings	master-index
leMPPDefinition 	(psubGR		("ptypeGuardRing")      (1)  		0
) ; MPP Definition 
; MPP Ring Object

; N type guard ring    	name   		obj-list 		spacings	master-index
leMPPDefinition 	(nwellGR 	("ntypeGuardRing")      (1)  		0
) ; MPP Definition 
; MPP Ring Object


; P type inside Pwell	name 		MasterPathName  EnclosedPathNames    OffsetPathNames 	SubRectangleNames  EncShapeNames
leMPPRingObject (  ptypeGuardRing	"defaultPath"   (diffEncPath pplusEncPath )  nil	(defaultContacts)  nil
;  net name  ExposedParameters
 vss userParams (name netName)
) ; MPP Ring Object

; N type inside Nwell	name 		MasterPathName  	EnclosedPathNames  	OffsetPathNames SubRectangleNames  EncShapeNames
leMPPRingObject (  ntypeGuardRing	"defaultPath"   (diffEncPath nplusEncPath nwellEncPath)   nil	(defaultContacts)  nil
;  net name  ExposedParameters
 vdd userParams (name netName)
) ; MPP Ring Object

;            		name        		layer 		purpose		width		path-style	conn    chop
leMPPMasterPath 	("defaultPath" 		"m1" 		drawing		0.1  		extend	 	t   	t
userParams (name width layer purpose conn chop)
) ; Master Path

;             		name 	            	layer 		purpose 	enclosure 	path-style 	conn    chop
leMPPEnclosedPath 	("diffEncPath"	 	"diff"		drawing 	0.045          	extend	 	t       nil
userParams (name layer purpose enclosure conn chop)
) ; Enclosed Path

;             		name 	            	layer 		purpose 	enclosure 	path-style 	conn    chop
leMPPEnclosedPath 	("pplusEncPath" 	"pplus"		drawing 	0.065          	extend	 	t  	nil
userParams (name layer purpose enclosure conn chop)
) ; Enclosed Path

;             		name 	            	layer 		purpose 	enclosure 	path-style 	conn    chop
leMPPEnclosedPath 	("nplusEncPath" 	"nplus"		drawing 	0.065          	extend	 	t 	nil
userParams (name layer purpose enclosure conn chop)
) ; Enclosed Path

;             		name 	            	layer 		purpose 	enclosure 	path-style 	conn    chop
leMPPEnclosedPath 	("nwellEncPath" 	"nwell"		drawing 	0.275          	extend	 	t   	nil
userParams (name layer purpose enclosure conn chop)
) ; Enclosed Path

;Sub Rectangles - contacts
;             name layer purpose width height conn chop enc EOL spa spaType numRows
leMPPSubRect (defaultContacts cont drawing 0.09 0.09 t t 0.005 0.005 0.1 fit 1
userParams (name layer purpose width height conn chop minEnclosure eol spacing spaceType numRows)
)

;Enclosed shape  name layer purpose leESEnclosure conn-flag leESExposedParameters
;leMPPEnclosedShape (encNWELL nwell drawing 0.275 t )
) ; leMPPControls


;;;;; MPP Definitions ############################


) ;controls


;********************************
; LAYER DEFINITION
;********************************
layerDefinitions(

 techPurposes(
 ;( PurposeName               Purpose#   Abbreviation )
 ;( -----------               --------   ------------ )
 ;User-Defined Purposes:

  ( dmy0                      0          dmy0         )
  ( dmy1                      1          dmy1         )
  ( dmy2                      2          dmy2         )
  ( dmy3                      3          dmy3         )
  ( dmy4                      4          dmy4         )
  ( dmy5                      5          dmy5         )
  ( dmy6                      6          dmy6         )
  ( dmy7                      7          dmy7         )
  ( dmy8                      8          dmy8         )
  ( dmy9                      9          dmy9         )
  ( waterMark                 63         waterMark    )
  ( dummy                     127        dummy        )
  ( subnode		      221	 subnode      )
  ( extract		      222        extract      )
 ;System-Reserved Purposes:
  ( redundant                 -8         red          )
  ( gapFill                   -7         gap          )
  ( annotation                -6         ann          )
  ( OPCAntiSerif              -5         opa          )
  ( OPCSerif                  -4         ops          )
  ( slot                      -3         slt          )
  ( fill                      -2         fil          )
  ( drawing                   -1         drw          )
  ( fatal                     223        fat          )
  ( critical                  224        crt          )
  ( soCritical                225        scr          )
  ( soError                   226        ser          )
  ( ackWarn                   227        ack          )
  ( info                      228        inf          )
  ( track                     229        trk          )
  ( blockage                  230        blk          )
  ( warning                   234        wng          )
  ( tool1                     235        tl1          )
  ( tool0                     236        tl0          )
  ( label                     237        lbl          )
  ( flight                    238        flt          )
  ( error                     239        err          )
  ( annotate                  240        ant          )
  ( drawing1                  241        dr1          )
  ( drawing2                  242        dr2          )
  ( drawing3                  243        dr3          )
  ( drawing4                  244        dr4          )
  ( drawing5                  245        dr5          )
  ( drawing6                  246        dr6          )
  ( drawing7                  247        dr7          )
  ( drawing8                  248        dr8          )
  ( drawing9                  249        dr9          )
  ( boundary                  250        bnd          )
  ( pin                       251        pin          )
  ( net                       253        net          )
  ( cell                      254        cel          )
  ( all                       255        all          )
 ) ;techPurposes
 techLayers(
 ;( LayerName                 Layer#     Abbreviation )
 ;( ---------                 ------     ------------ )
 ;User-Defined Layers:
  ( nwell                     1         nwell       )
  ( diff                      2         diff        )
  ( poly                      3         poly        )
  ( pplus                     4         pplus       )
  ( nplus                     5         nplus       )
  ( rpoly                     6         rpoly       )
  ( cont                      7         cont        )
  ( m1                        8         m1          )
  ( m1text                    9         m1text      )
  ( m2                       10         m2          )
  ( m2text                   11         m2text      )
  ( m3                       12         m3          )
  ( m3text                   13         m3text      )
  ( m4                       14         m4          )
  ( m4text                   15         m4text      )
  ( v1                       16         v1          )
  ( v2                       17         v2          )
  ( v3                       18         v3          )
  ( exclude                  19         exclude     )
  ( mtcap                    20         mtcap       )
  ( mbcap                    21         mbcap       )
  ( dnw                      22         dnw         )
  ( nwdmy                    23         nwdmy       )
  ( rpdmy                    24         rpdmy       )
  ( diode                    25         diode       )
  ( nat                      26         nat         )
  ( diff25                   27         diff25      )
  ( rmarker                  28         rmarker     )
  ( hrimp                    29         hrimp       )
  ( inddmy                   30         inddmy     )
  ( varmarker                31         varmarker   )
  ( rmdmy                    32         rmdmy       )
  ( medvtn                   33         medvtn      )
  ( medvtp                   34         medvtp      )
  ( diff18                   35         diff18      )
  ( diff33                   36         diff33      )
  ( lowvtn                   37         lowvtn      )
  ( lowvtp                   38         lowvtp      )
  ( highvtn                  39         highvtn     )
  ( highvtp                  40         highvtp     )
  ( polytext                 41         polytext    )
  ( bjtdummy                 49         bjtdummy    )
  ( iplayer                  63         iplayer     )
  ( psub                     64         psub        )
  ( pindummy                 65         pindummy    )
  ( rtermmarker              66         rtermmarker )
  ( ctmdmy                   67         ctmdmy      )
  ( momdmy                   68         momdmy      )
  ( rfdmy                    69         rfdmy       )
  ( boundary                 127        boundary    )
  ( m5                       70         m5          )
  ( m5text                   71         m5text      )
  ( m6                       72         m6          )
  ( m6text                   73         m6text      )
  ( m7                       74         m7          )
  ( m7text                   75         m7text      )
  ( m8                       76         m8          )
  ( m8text                   77         m8text      )
  ( m9                       78         m9          )
  ( m9text                   79         m9text      )
  ( v4                       80         v4          )
  ( v5                       81         v5          )
  ( v6                       82         v6          )
  ( v7                       83         v7          )
  ( v8                       84         v8          ) 
 ;System-Reserved Layers:
  ( Unrouted                  200        Unroute      )
  ( Row                       201        Row          )
  ( Group                     202        Group        )
  ( Cannotoccupy              203        noOcupy      )
  ( Canplace                  204        Canplac      )
  ( hardFence                 205        hardFnc      )
  ( softFence                 206        softFnc      )
  ( y0                        207        y0           )
  ( y1                        208        y1           )
  ( y2                        209        y2           )
  ( y3                        210        y3           )
  ( y4                        211        y4           )
  ( y5                        212        y5           )
  ( y6                        213        y6           )
  ( y7                        214        y7           )
  ( y8                        215        y8           )
  ( y9                        216        y9           )
  ( designFlow                217        dsnFlow      )
  ( stretch                   218        stretch      )
  ( edgeLayer                 219        edgeLyr      )
  ( changedLayer              220        chngLyr      )
  ( unset                     221        unset        )
  ( unknown                   222        unknown      )
  ( spike                     223        spike        )
  ( hiz                       224        hiz          )
  ( resist                    225        resist       )
  ( drive                     226        drive        )
  ( supply                    227        supply       )
  ( wire                      228        wire         )
  ( pin                       229        pin          )
  ( text                      230        text         )
  ( device                    231        device       )
  ( border                    232        border       )
  ( snap                      233        snap         )
  ( align                     234        align        )
  ( prBoundary                235        prBndry      )
  ( instance                  236        instnce      )
  ( annotate                  237        anotate      )
  ( marker                    238        marker       )
  ( select                    239        select       )
  ( grid                      251        grid         )
  ( axis                      252        axis         )
  ( hilite                    253        hilite       )
  ( background                254        bkground     )
 ) ;techLayers

 techLayerPurposePriorities(
 ;layers are ordered from lowest to highest priority
 ;( LayerName                 Purpose    )
 ;( ---------                 -------    )
  ( background                drawing    )
  ( grid                      drawing    )
  ( grid                      drawing1   )
  ( exclude                   blockage   )
  ( nwell                     subnode    )
  ( diff                      subnode    )
  ( poly                      subnode    )
  ( cont                      subnode    )
  ( nplus                     subnode    )
  ( pplus                     subnode    )
  ( m1                        subnode    )
  ( v1                        subnode    )
  ( m2                        subnode    )
  ( v2                        subnode    )
  ( m3                        subnode    )
  ( v3                        subnode    )
  ( m4                        subnode    )
  ( v4			      subnode	 )
  ( m5                        subnode    )
  ( v5			      subnode	 )
  ( m6                        subnode    )
  ( v6			      subnode	 )
  ( m7                        subnode    )
  ( v7			      subnode	 )
  ( m8                        subnode    )
  ( v8			      subnode	 )
  ( m9                        subnode    )
  
  ( psub                      drawing    )
  ( psub                      subnode)
  ( dnw                       drawing    )
  ( nwell                     drawing    )
  ( nwell                     net        )
  ( diff                      drawing    )
  ( diff                      net        )
  ( diff25                    drawing    )
  ( diff18                    drawing    )
  ( diff33                    drawing    )
  ( pplus                     drawing    )
  ( pplus                     net        )
  ( nplus                     drawing    )
  ( nplus                     net        )
  ( nat                       drawing    )
  ( poly                      drawing    )
  ( poly                      net        )
  ( poly                      pin        )
  ( cont                      drawing    )
  ( cont                      net        )
  ( pindummy                  drawing    )
  ( pindummy                  pin        )
  ( m1                        drawing    )
  ( m1                        net        )
  ( m1                        pin        )
  ( v1                        drawing    )
  ( v1                        net        )
  ( m2                        drawing    )
  ( m2                        net        )
  ( m2                        pin        )
  ( v2                        drawing    )
  ( v2                        net        )
  ( m3                        drawing    )
  ( m3                        net        )
  ( m3                        pin        )
  ( v3                        drawing    )
  ( v3                        net        )
  ( m4                        drawing    )
  ( m4                        net        )
  ( m4                        pin        )
  ( v4                        drawing    )
  ( v4                        net        )  
  ( m5                        drawing    )
  ( m5                        net        )
  ( m5                        pin        )
  ( v5                        drawing    )
  ( v5                        net        )
  ( m6                        drawing    )
  ( m6                        net        )
  ( m6                        pin        )
  ( v6                        drawing    )
  ( v6                        net        )
  ( m7                        drawing    )
  ( m7                        net        )
  ( m7                        pin        )
  ( v7                       drawing    )
  ( v7                        net        )
  ( m8                        drawing    )
  ( m8                        net        )
  ( m8                        pin        )
  ( v8                        drawing    )
  ( v8                        net        )
  ( m9                        drawing    )
  ( m9                        net        )
  ( m9                        pin        )
  ( diff                      dummy      )
  ( poly                      dummy      )
  ( m1                        dummy      )
  ( m2                        dummy      )
  ( m3                        dummy      )
  ( m4                        dummy      )
  ( m5                        dummy      )
  ( m6                        dummy      )
  ( m7                        dummy      )
  ( m8                        dummy      )
  ( m9                        dummy      )
  ( m1                        blockage   )
  ( m2                        blockage   )
  ( m3                        blockage   )
  ( m4                        blockage   )
  ( m5                        blockage   )
  ( m6                        blockage   )
  ( m7                        blockage   )
  ( m8                        blockage   )
  ( m9                        blockage   )
  ( m1                        slot       )
  ( m2                        slot       )
  ( m3                        slot       )
  ( m4                        slot       )
  ( m5                        slot       )
  ( m6                        slot       )
  ( m7                        slot       )
  ( m8                        slot       )
  ( m9                        slot       )
  ( cont                      boundary   )
  ( medvtp                    drawing    )
  ( medvtn                    drawing    )
  ( lowvtp                    drawing    )
  ( lowvtn                    drawing    )
  ( highvtp                   drawing    )
  ( highvtn                   drawing    )
  ( rmarker                   drawing    )
  ( rtermmarker               drawing    )
  ( rpoly                     drawing    )
  ( hrimp                     drawing    )
  ( mtcap                     drawing    )
  ( mbcap                     drawing    )
  ( varmarker                 drawing    )
  ( inddmy                    drawing    )
  ( bjtdummy                  drawing    )
  ( nwdmy                     drawing    )
  ( rmdmy                     drawing    )
  ( ctmdmy                    drawing    )
  ( rfdmy                     drawing    )
  ( diode                     drawing    )
  ( momdmy                    dmy1       )
  ( momdmy                    dmy2       )
  ( momdmy                    dmy3       )
  ( momdmy                    dmy4       )
  ( momdmy                    dmy5       )
  ( momdmy                    dmy6       )
  ( momdmy                    dmy7       )
  ( momdmy                    dmy8       )
  ( momdmy                    dmy9       )
  ( m1text                    drawing    )
  ( m2text                    drawing    )
  ( m3text                    drawing    )
  ( m4text                    drawing    )
  ( m5text                    drawing    )
  ( m6text                    drawing    )
  ( m7text                    drawing    )
  ( m8text                    drawing    )
  ( m9text                    drawing    )
  ( polytext                  drawing    )
  ( iplayer                   waterMark  )

  ( annotate                  drawing    )
  ( annotate                  drawing1   )
  ( annotate                  drawing2   )
  ( annotate                  drawing3   )
  ( annotate                  drawing4   )
  ( annotate                  drawing5   )
  ( annotate                  drawing6   )
  ( annotate                  drawing7   )
  ( annotate                  drawing8   )
  ( annotate                  drawing9   )
  ( instance                  drawing    )
  ( instance                  label      )
  ( prBoundary                drawing    )
  ( prBoundary                boundary   )
  ( prBoundary                label      )
  ( align                     drawing    )
  ( hardFence                 drawing    )
  ( softFence                 drawing    )
  ( text                      drawing    )
  ( text                      drawing1   )
  ( text                      drawing2   )
  ( border                    drawing    )
  ( border                    boundary   )
  ( device                    drawing    )
  ( device                    label      )
  ( device                    drawing1   )
  ( device                    drawing2   )
  ( device                    annotate   )
  ( wire                      drawing    )
  ( wire                      label      )
  ( wire                      flight     )
  ( pin                       label      )
  ( pin                       drawing    )
  ( pin                       annotate   )
  ( axis                      drawing    )
  ( edgeLayer                 drawing    )
  ( edgeLayer                 pin        )
  ( snap                      drawing    )
  ( snap                      boundary   )
  ( stretch                   drawing    )
  ( y0                        drawing    )
  ( y1                        drawing    )
  ( y2                        drawing    )
  ( y3                        drawing    )
  ( y4                        drawing    )
  ( y5                        drawing    )
  ( y6                        drawing    )
  ( y7                        drawing    )
  ( y8                        drawing    )
  ( y9                        drawing    )
  ( y0                        flight     )
  ( y1                        flight     )
  ( y2                        flight     )
  ( y3                        flight     )
  ( y4                        flight     )
  ( y5                        flight     )
  ( y6                        flight     )
  ( y7                        flight     )
  ( y8                        flight     )
  ( y9                        flight     )
  ( hilite                    drawing    )
  ( hilite                    drawing1   )
  ( hilite                    drawing2   )
  ( hilite                    drawing3   )
  ( hilite                    drawing4   )
  ( hilite                    drawing5   )
  ( hilite                    drawing6   )
  ( hilite                    drawing7   )
  ( hilite                    drawing8   )
  ( hilite                    drawing9   )
  ( select                    drawing    )
  ( drive                     drawing    )
  ( hiz                       drawing    )
  ( resist                    drawing    )
  ( spike                     drawing    )
  ( supply                    drawing    )
  ( unknown                   drawing    )
  ( unset                     drawing    )
  ( designFlow                drawing    )
  ( designFlow                drawing1   )
  ( designFlow                drawing2   )
  ( designFlow                drawing3   )
  ( designFlow                drawing4   )
  ( designFlow                drawing5   )
  ( designFlow                drawing6   )
  ( designFlow                drawing7   )
  ( designFlow                drawing8   )
  ( designFlow                drawing9   )
  ( changedLayer              tool0      )
  ( changedLayer              tool1      )
  ( marker                    warning    )
  ( marker                    error      )
  ( marker                    annotate   )
  ( marker                    info       )
  ( marker                    ackWarn    )
  ( marker                    soError    )
  ( marker                    soCritical )
  ( marker                    critical   )
  ( marker                    fatal      )
  ( Row                       drawing    )
  ( Row                       label      )
  ( Row                       boundary   )
  ( Group                     drawing    )
  ( Group                     label      )
  ( Group                     boundary   )
  ( Cannotoccupy              drawing    )
  ( Cannotoccupy              boundary   )
  ( Canplace                  drawing    )
  ( Unrouted                  drawing    )
  ( Unrouted                  drawing1   )
  ( Unrouted                  drawing2   )
  ( Unrouted                  drawing3   )
  ( Unrouted                  drawing4   )
  ( Unrouted                  drawing5   )
  ( Unrouted                  drawing6   )
  ( Unrouted                  drawing7   )
  ( Unrouted                  drawing8   )
  ( Unrouted                  drawing9   )
  ( Unrouted                  track      )


 ) ;techLayerPurposePriorities

 techDisplays(
 ;( LayerName    Purpose      Packet          Vis Sel Con2ChgLy DrgEnbl Valid )
 ;( ---------    -------      ------          --- --- --------- ------- ----- )

  ( background   drawing      background       t nil t nil nil )
  ( grid         drawing      grid             t nil t nil nil )
  ( grid         drawing1     grid1            t nil t nil nil )
  ( annotate     drawing      annotate         t t t t nil )
  ( annotate     drawing1     annotate1        t t t t nil )
  ( annotate     drawing2     annotate2        t t t t nil )
  ( annotate     drawing3     annotate3        t t t t nil )
  ( annotate     drawing4     annotate4        t t t t nil )
  ( annotate     drawing5     annotate5        t t t t nil )
  ( annotate     drawing6     annotate6        t t t t nil )
  ( annotate     drawing7     annotate7        t t t t nil )
  ( annotate     drawing8     annotate8        t t t t nil )
  ( annotate     drawing9     annotate9        nil t t t nil )
  ( instance     drawing      instance         t t t t nil )
  ( instance     label        instanceLbl      t t t t nil )
  ( prBoundary   drawing      prBoundary       t t t t nil )
  ( prBoundary   boundary     prBoundaryBnd    t t t t nil )
  ( prBoundary   label        prBoundaryLbl    t t t t nil )
  ( align        drawing      align            t t t t nil )
  ( hardFence    drawing      hardFence        t t t t nil )
  ( softFence    drawing      softFence        t t t t nil )

  ( dnw          drawing      dnw              t t nil t t )
  ( nwell        drawing      nwell            t t nil t t )
  ( diff         drawing      sldiff           t t nil t t )
  ( medvtp       drawing      medvtp           t t nil t t )
  ( medvtn       drawing      medvtn           t t nil t t )
  ( lowvtp       drawing      lowvtp           t t nil t t )
  ( lowvtn       drawing      lowvtn           t t nil t t )
  ( highvtp      drawing      highvtp          t t nil t t )
  ( highvtn      drawing      highvtn          t t nil t t )
  ( nat          drawing      nat              t t nil t t )
  ( diff25       drawing      diff25           t t nil t t )
  ( diff18       drawing      diff18           t t nil t t )
  ( diff33       drawing      diff33           t t nil t t )
  ( poly         drawing      poly             t t nil t t )
  ( poly         pin          polyPin          t t t   t t )
  ( pplus        drawing      pplus            t t nil t t )
  ( nplus        drawing      nplus            t t nil t t )
  ( rpoly        drawing      rpoly            t t nil t t )
  ( cont         drawing      cont             t t nil t t )
  ( cont         boundary     contb            t t nil t t )
  ( m1           drawing      m1               t t nil t t )
  ( pindummy     drawing      pindummy         nil nil nil nil nil )
  ( v1           drawing      v1               t t nil t t )
  ( m2           drawing      m2               t t nil t t )
  ( v2           drawing      v2               t t nil t t )
  ( m3           drawing      m3               t t nil t t )
  ( v3           drawing      v3               t t nil t t )
  ( m4           drawing      m4               t t nil t t )
  ( v4           drawing      v4               t t nil t t )
  ( m5           drawing      m5               t t nil t t )
  ( v5           drawing      v5               t t nil t t )
  ( m6           drawing      m6               t t nil t t )
  ( v6           drawing      v6               t t nil t t )
  ( m7           drawing      m7               t t nil t t )
  ( v7           drawing      v7               t t nil t t )
  ( m8           drawing      m8               t t nil t t )
  ( v8           drawing      v8               t t nil t t )
  ( m9           drawing      m9               t t nil t t )
  ( psub         drawing      psub             t t nil t t )
  ( psub         subnode      psub             t t nil t t )
  ( m1           pin          m1Pin            t t nil t t )
  ( pindummy     pin          pindummyPin      nil nil nil nil nil )
  ( m2           pin          m2Pin            t t nil t t )
  ( m3           pin          m3Pin            t t nil t t )
  ( m4           pin          m4Pin            t t nil t t )
  ( m5           pin          m5Pin            t t nil t t )
  ( m6           pin          m6Pin            t t nil t t )
  ( m7           pin          m7Pin            t t nil t t )
  ( m8           pin          m8Pin            t t nil t t )
  ( m9           pin          m9Pin            t t nil t t )
  ( m1           blockage     m1Blk            t t nil t t )
  ( m2           blockage     m2Blk            t t nil t t )
  ( m3           blockage     m3Blk            t t nil t t )
  ( m4           blockage     m4Blk            t t nil t t )
  ( m5           blockage     m5Blk            t t nil t t )
  ( m6           blockage     m6Blk            t t nil t t )
  ( m7           blockage     m7Blk            t t nil t t )
  ( m8           blockage     m8Blk            t t nil t t )
  ( m9           blockage     m9Blk            t t nil t t )
  ( m1           boundary     m1b              t t nil t nil )
  ( m2           boundary     m2b              t t nil t nil )
  ( m3           boundary     m3b              t t nil t nil )
  ( m4           boundary     m4b              t t nil t nil )
  ( m5           boundary     m5b              t t nil t nil )
  ( m6           boundary     m6b              t t nil t nil )
  ( m7           boundary     m7b              t t nil t nil )
  ( m8           boundary     m8b              t t nil t nil )
  ( m9           boundary     m9b              t t nil t nil )
  ( rmarker      drawing      rpdmy            t t nil t t )
  ( rtermmarker  drawing      rtdmy            t t nil t t )
  ( v1           boundary     v1b              t t nil t nil )
  ( v2           boundary     v2b              t t nil t nil )
  ( v3           boundary     v3b              t t nil t nil )
  ( v4           boundary     v4b              t t nil t nil )
  ( v5           boundary     v5b              t t nil t nil )
  ( v6           boundary     v6b              t t nil t nil )
  ( v7           boundary     v7b              t t nil t nil )
  ( v8           boundary     v8b              t t nil t nil )
  ( hrimp        drawing      hrimp            t t nil t t )
  ( mtcap        drawing      mtcap            t t nil t t )
  ( mbcap          drawing      mbcap              t t nil t t )
  ( varmarker    drawing      varmarker        t t nil t t )
  ( inddmy       drawing      inddmy           t t nil t t )
  ( bjtdummy     drawing      bjtdummy         t t nil t t )
  ( nwdmy        drawing      nwdmy            t t nil t t )
  ( rmdmy        drawing      rmdmy            t t nil t t )
  ( ctmdmy       drawing      ctmdmy           t t nil t t )
  ( rfdmy        drawing      rfdmy            t t nil t t )
  ( diode        drawing      diode            t t nil t t )
  ( exclude      blockage     exclude          t t nil t t )
  ( diff         dummy        diffDmy          t t nil t t )
  ( poly         dummy        polyDmy          t t nil t t )
  ( m1           dummy        m1Pin            t t nil t t )
  ( m2           dummy        m2Pin            t t nil t t )
  ( m3           dummy        m3Pin            t t nil t t )
  ( m4           dummy        m4Pin            t t nil t t )
  ( m5           dummy        m5Pin            t t nil t t )
  ( m6           dummy        m6Pin            t t nil t t )
  ( m7           dummy        m7Pin            t t nil t t )
  ( m8           dummy        m8Pin            t t nil t t )
  ( m9           dummy        m9Pin            t t nil t t )
  ( momdmy       dmy1         momDmy1          t t nil t t )
  ( momdmy       dmy2         momDmy2          t t nil t t )
  ( momdmy       dmy3         momDmy3          t t nil t t )
  ( momdmy       dmy4         momDmy4          t t nil t t )
  ( momdmy       dmy5         momDmy5          t t nil t t )
  ( momdmy       dmy6         momDmy6          t t nil t t )
  ( momdmy       dmy7         momDmy7          t t nil t t )
  ( momdmy       dmy8         momDmy8          t t nil t t )
  ( momdmy       dmy9         momDmy9          t t nil t t )
  ( iplayer      waterMark    ipLayer          t t nil t t )
  ( m1           slot         m1slot           t t nil t t )
  ( m2           slot         m2slot           t t nil t t )
  ( m3           slot         m3slot           t t nil t t )
  ( m4           slot         m4slot           t t nil t t )
  ( m5           slot         m5slot           t t nil t t )
  ( m6           slot         m6slot           t t nil t t )
  ( m7           slot         m7slot           t t nil t t )
  ( m8           slot         m8slot           t t nil t t )
  ( m9           slot         m9slot           t t nil t t )
  ( m1text       drawing      m1txt            t t nil t t )
  ( m2text       drawing      m2txt            t t nil t t )
  ( m3text       drawing      m3txt            t t nil t t )
  ( m4text       drawing      m4txt            t t nil t t )
  ( m5text       drawing      m5txt            t t nil t t )
  ( m6text       drawing      m6txt            t t nil t t )
  ( m7text       drawing      m7txt            t t nil t t )
  ( m8text       drawing      m8txt            t t nil t t )
  ( m9text       drawing      m9txt            t t nil t t )
  ( polytext     drawing      polytxt          t t nil t t )

  ( text         drawing      text             t t t t t )
  ( text         drawing1     text1            t t t t nil )
  ( text         drawing2     text2            t t t t nil )
  ( border       drawing      border           t t t t nil )
  ( device       drawing      device           t t t t nil )
  ( device       label        deviceLbl        t t t t nil )
  ( device       drawing1     device1          t t t t nil )
  ( device       drawing2     device2          t t t t nil )
  ( device       annotate     deviceAnt        t t t t nil )
  ( wire         drawing      wire             t t t t nil )
  ( wire         label        wireLbl          t t t t nil )
  ( wire         flight       wireFlt          t t t t nil )
  ( pin          label        pinLbl           t t t t nil )
  ( pin          drawing      pin              t t t t nil )
  ( pin          annotate     pinAnt           t t t t nil )
  ( axis         drawing      axis             t nil t t nil )
  ( edgeLayer    drawing      edgeLayer        t t t t nil )
  ( edgeLayer    pin          edgeLayerPin     t t t t nil )
  ( snap         drawing      snap             t t t t nil )
  ( stretch      drawing      stretch          t t t t nil )
  ( y0           drawing      y0               t t t t nil )
  ( y1           drawing      y1               t t t t nil )
  ( y2           drawing      y2               t t t t nil )
  ( y3           drawing      y3               t t t t nil )
  ( y4           drawing      y4               t t t t nil )
  ( y5           drawing      y5               t t t t nil )
  ( y6           drawing      y6               t t t t nil )
  ( y7           drawing      y7               t t t t nil )
  ( y8           drawing      y8               t t t t nil )
  ( y9           drawing      y9               t t t t nil )
  ( hilite       drawing      hilite           t t t t nil )
  ( hilite       drawing1     hilite1          t t t t nil )
  ( hilite       drawing2     hilite2          t t t t nil )
  ( hilite       drawing3     hilite3          t t t t nil )
  ( hilite       drawing4     hilite4          t t t t nil )
  ( hilite       drawing5     hilite5          t t t t nil )
  ( hilite       drawing6     hilite6          t t t t nil )
  ( hilite       drawing7     hilite7          t t t t nil )
  ( hilite       drawing8     hilite8          t t t t nil )
  ( hilite       drawing9     hilite9          t t t t nil )
  ( select       drawing      select           t t t t nil )
  ( drive        drawing      drive            t t t t nil )
  ( hiz          drawing      hiz              t t t t nil )
  ( resist       drawing      resist           t t t t nil )
  ( spike        drawing      spike            t t t t nil )
  ( supply       drawing      supply           t t t t nil )
  ( unknown      drawing      unknown          t t t t nil )
  ( unset        drawing      unset            t t t t nil )
  ( designFlow   drawing      designFlow       t t t nil nil )
  ( designFlow   drawing1     designFlow1      t t t nil nil )
  ( designFlow   drawing2     designFlow2      t t t nil nil )
  ( designFlow   drawing3     designFlow3      t t t nil nil )
  ( designFlow   drawing4     designFlow4      t t t nil nil )
  ( designFlow   drawing5     designFlow5      t t t nil nil )
  ( designFlow   drawing6     designFlow6      t t t nil nil )
  ( designFlow   drawing7     designFlow7      t t t nil nil )
  ( designFlow   drawing8     designFlow8      t t t nil nil )
  ( designFlow   drawing9     designFlow9      t t t nil nil )
  ( changedLayer tool0        changedLayerTl0  nil nil t nil nil )
  ( changedLayer tool1        changedLayerTl1  nil nil t nil nil )
  ( marker       warning      markerWarn       t t t t nil )
  ( marker       error        markerErr        t t t t nil )
  ( Row          drawing      Row              t t t t nil )
  ( Row          label        RowLbl           t nil t t nil )
  ( Group        drawing      Group            t t t t nil )
  ( Group        label        GroupLbl         t nil t t nil )
  ( Cannotoccupy drawing      Cannotoccupy     t t t t nil )
  ( Cannotoccupy boundary     CannotoccupyBnd  t t t t nil )
  ( Canplace     drawing      Canplace         t t t t nil )
  ( Unrouted     drawing      Unrouted         t t t t nil )
  ( Unrouted     drawing1     Unrouted1        t t t t nil )
  ( Unrouted     drawing2     Unrouted2        t t t t nil )
  ( Unrouted     drawing3     Unrouted3        t t t t nil )
  ( Unrouted     drawing4     Unrouted4        t t t t nil )
  ( Unrouted     drawing5     Unrouted5        t t t t nil )
  ( Unrouted     drawing6     Unrouted6        t t t t nil )
  ( Unrouted     drawing7     Unrouted7        t t t t nil )
  ( Unrouted     drawing8     Unrouted8        t t t t nil )
  ( Unrouted     drawing9     Unrouted9        t t t t nil )
  ( marker       annotate     markerAno        t t t t nil )
  ( marker       info         markerInf        t t t t nil )
  ( marker       ackWarn      markerAck        t t t t nil )
  ( marker       soError      markerSer        t t t t nil )
  ( marker       soCritical   markerScr        t t t t nil )
  ( marker       critical     markerCrt        t t t t nil )
  ( marker       fatal        markerFat        t t t t nil )
  ( snap         boundary     snap             t nil t t nil )
  ( Row          boundary     RowBnd           t t t t nil )
  ( Unrouted     track        UnroutedTrk      t t t t nil )
  ( Group        boundary     GroupBnd         t nil t t nil )
  ( y0           flight       y0Flt            t t t t nil )                
  ( y1           flight       y1Flt            t t t t nil )          
  ( y2           flight       y2Flt            t t t t nil )          
  ( y3           flight       y3Flt            t t t t nil )          
  ( y4           flight       y4Flt            t t t t nil )          
  ( y5           flight       y5Flt            t t t t nil )          
  ( y6           flight       y6Flt            t t t t nil )          
  ( y7           flight       y7Flt            t t t t nil )          
  ( y8           flight       y8Flt            t t t t nil )          
  ( y9           flight       y9Flt            t t t t nil )          
  ( border       boundary     area             t nil t t nil )
  
  ( nwell        net          nwell            t t nil t nil )
  ( nwell        subnode      nwell            t t nil t nil )
  ( diff         net          sldiff           t t nil t nil )
  ( diff         subnode      sldiff           t t nil t nil )
  ( poly         net          polynet          t t nil t nil )
  ( poly         subnode      poly             t t nil t nil )
  ( cont         net          contnet          t t nil t nil )
  ( cont         subnode      cont             t t nil t nil )
  ( nplus        net          nplus            t t nil t nil )
  ( nplus        subnode      nplus            t t nil t nil )
  ( pplus        net          pplus            t t nil t nil )
  ( pplus        subnode      pplus            t t nil t nil )
  ( m1           net          m1net            t t nil t nil )
  ( m1           subnode      m1               t t nil t nil )
  ( v1           net          v1net            t t nil t nil )
  ( v1           subnode      v1               t t nil t nil )
  ( m2           net          m2net            t t nil t nil )
  ( m2           subnode      m2               t t nil t nil )
  ( v2           net          v2net            t t nil t nil )
  ( v2           subnode      v2               t t nil t nil )
  ( m3           net          m3net            t t nil t nil )
  ( m3           subnode      m3               t t nil t nil )
  ( v3           net          v3net            t t nil t nil )
  ( v3           subnode      v3               t t nil t nil )
  ( m4           net          m4net            t t nil t nil )
  ( m4           subnode      m4               t t nil t nil )
  ( v4           net          v4net            t t nil t nil )
  ( v4           subnode      v4               t t nil t nil )
  ( m5           net          m5               t t nil t nil )
  ( m5           subnode      m5               t t nil t nil )
  ( v5           net          v5net            t t nil t nil )
  ( v5           subnode      v5               t t nil t nil )
  ( m6           net          m6               t t nil t nil )
  ( m6           subnode      m6               t t nil t nil )
  ( v6           net          v6net            t t nil t nil )
  ( v6           subnode      v6               t t nil t nil )
  ( m7           net          m7               t t nil t nil )
  ( m7           subnode      m7               t t nil t nil )
  ( v7           net          v7net            t t nil t nil )
  ( v7           subnode      v7               t t nil t nil )
  ( m8           net          m8               t t nil t nil )
  ( m8           subnode      m8               t t nil t nil )
  ( v8           net          v8net            t t nil t nil )
  ( v8           subnode      v8               t t nil t nil )
  ( m9           net          m9               t t nil t nil )
  ( m9           subnode      m9               t t nil t nil )
  
 ) ;techDisplays

 techLayerProperties(
 ;( PropName               Layer1 [ Layer2 ]            PropValue )
 ;( --------               ------ ----------            --------- )
  ( sheetResistance        nwell                         550.0  )
  ( sheetResistance        poly                          6.34   )
  ( sheetResistance        diff                          5.525  )
  ( sheetResistance        v1                            0.0016 )
  ( sheetResistance        v2                            0.0016 )
  ( sheetResistance        v3                            0.0016 )
  ( sheetResistance        m1                            0.115  )
  ( sheetResistance        m2                            0.086  )
  ( sheetResistance        m3                            0.086  )
  ( sheetResistance        m4                            0.086  )
  ( sheetResistance        m5                            0.086  )
  ( sheetResistance        m6                            0.086  )
  ( sheetResistance        m7                            0.086  )
  ( sheetResistance        m8                            0.086  )
  ( sheetResistance        m9                            0.04   )
  
  ( areaCapacitance        poly                           6.950000e-05 )
  ( edgeCapacitance        poly                           4.503000e-11 )  
  ( areaCapacitance        m1                             2.620000e-05 )
  ( edgeCapacitance        m1                             3.163000e-11 )
  ( areaCapacitance        m2                             1.180000e-05 )
  ( edgeCapacitance        m2                             2.345000e-11 )
  ( areaCapacitance        m3                             7.870000e-06 )
  ( edgeCapacitance        m3                             1.028000e-11 )
  ( areaCapacitance        m4                             7.870000e-06 )
  ( edgeCapacitance        m4                             1.028000e-11 )
  ( areaCapacitance        m5                             7.870000e-06 )
  ( edgeCapacitance        m5                             1.028000e-11 )
  ( areaCapacitance        m6                             7.870000e-06 )
  ( edgeCapacitance        m6                             1.028000e-11 )
  ( areaCapacitance        m7                             7.870000e-06 )
  ( edgeCapacitance        m7                             1.028000e-11 )
  ( areaCapacitance        m8                             7.870000e-06 )
  ( edgeCapacitance        m8                             1.028000e-11 )
  ( areaCapacitance        m9                             4.9980000e-06)
  ( edgeCapacitance        m8                             1.110000e-11 )
  
 ) ;techLayerProperties

 techDerivedLayers(
 ;( DerivedLayerName          #          composition  )
 ;( ----------------          ------     ------------ )
 ) ;techDerivedLayers

) ;layerDefinitions


;********************************
; LAYER RULES
;********************************
layerRules(

 equivalentLayers(
 ;( list of layers )
 ;( -------------- )
 ) ;equivalentLayers

 functions(
 ;( layer                       function        [maskNumber])
 ;( -----                       --------        ------------)
  ( psub                        "pWell"         1            )
  ( nwell                    	"nWell"      	2            )
  ( diff                    	"diffusion"     3            )
  ( diff18                    	"diffusion"     4            )
  ( diff25                    	"diffusion"     5            )
  ( diff33                    	"diffusion"     6            )
  ( pplus                    	"pImplant"      7            )
  ( nplus                    	"nImplant"      8            )
  ( rpoly                    	"other"      	9            )
  ( poly                    	"poly"      	10            )
  ( cont                     	"cut"           11            )
  ( m1                   	"metal"     	12            )
  ( v1                    	"cut"       	13           )
  ( m2                   	"metal"     	14           )
  ( v2                    	"cut"       	15           )
  ( m3                   	"metal"     	16           )
  ( v3                    	"cut"       	17           )
  ( m4                   	"metal"     	18           )
  ( v4                    	"cut"       	19           )
  ( m5                   	"metal"     	20           )
  ( v5                    	"cut"       	21           )
  ( m6                   	"metal"     	22           )
  ( v6                    	"cut"       	23           )
  ( m7                   	"metal"     	24           )
  ( v7                    	"cut"       	25           )
  ( m8                   	"metal"     	26           )
  ( v8                    	"cut"       	27           )
  ( m9                   	"metal"     	28           )
  ( mtcap                    	"other"      	29           )
  ( mbcap                    	"other"      	30           )
  ( rmarker                    	"other"      	31           )
  ( rmdmy                    	"other"      	32           )
  ( ctmdmy                    	"other"      	33           )
  ( rfdmy                    	"other"      	34           )
  ( iplayer                    	"other"      	35           )
 ) ;functions

 mfgResolutions(
 ;( layer                       mfgResolution )
 ;( -----                       ------------- )
  ( dnw                  	0.005 )
  ( nwell                    	0.005 )
  ( diff                     	0.005 )
  ( medvtp                     	0.005 )
  ( medvtn                     	0.005 )
  ( lowvtp                     	0.005 )
  ( lowvtn                     	0.005 )
  ( highvtp                    	0.005 )
  ( highvtn                    	0.005 )
  ( nat                      	0.005 )
  ( diff25                     	0.005 )
  ( diff18                     	0.005 )
  ( diff33                     	0.005 )
  ( poly                    	0.005 )
  ( pplus                     	0.005 )
  ( nplus                     	0.005 )
  ( rpoly                      	0.005 )
  ( cont                     	0.005 )
  ( m1                   	0.005 )
  ( v1                    	0.005 )
  ( m2                   	0.005 )
  ( v2                    	0.005 )
  ( m3                   	0.005 )
  ( v3                    	0.005 )
  ( m4                   	0.005 )
  ( v4                    	0.005 )
  ( m5                   	0.005 ) 
  ( v5                    	0.005 )
  ( m6                   	0.005 )
  ( v6                    	0.005 )
  ( m7                   	0.005 )
  ( v7                    	0.005 )
  ( m8                   	0.005 )
  ( v8                    	0.005 )
  ( m9                   	0.005 )
  ( rmarker                  	0.005 )
  ( rtermmarker                	0.005 )
  ( hrimp                      	0.005 )
  ( mtcap                     	0.005 )
  ( varmarker                  	0.005 )
  ( inddmy                   	0.005 )
  ( bjtdummy                 	0.005 )
  ( nwdmy                  	0.005 )
  ( rmdmy                  	0.005 )
  ( ctmdmy                  	0.005 )
  ( rfdmy                  	0.005 )
  ( diode                 	0.005 )
  ( momdmy                 	0.005 )
  ( exclude                    	0.005 )
  ( psub                    	0.005 )
  ( iplayer                    	0.005 )

 ) ;mfgResolutions

 routingDirections(
 ;( layer                       direction     )
 ;( -----                       ---------     )
  ( m1 horizontal )
  ( m2 vertical   )
  ( m3 horizontal )
  ( m4 vertical   )
 ) ;routingDirections

 currentDensity(
 ;( rule                	layer1    	layer2    	value    )
 ;( ----                	------    	------    	-----    )
 ) ;currentDensity

 currentDensityTables(
 ;( rule                	layer1    
 ;  (( index1Definitions	[index2Definitions]) [defaultValue] )
 ;  (table))
 ;( ----------------------------------------------------------------------)
 ) ;currentDensityTables

) ;layerRules


;********************************
; VIADEFS
;********************************
viaDefs(

 standardViaDefs(
 ;( viaDefName	layer1	layer2	(cutLayer cutWidth cutHeight [resistancePerCut]) 
 ;   (cutRows	cutCol	(cutSpace)) 
 ;   (layer1Enc) (layer2Enc)	(layer1Offset)	(layer2Offset)	(origOffset) 
 ;   [implant1	 (implant1Enc)	[implant2	(implant2Enc)]]) 
 ;( -------------------------------------------------------------------------- ) 

  ( via89       	m8      m9      	("v8" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.01 0.04)	(0.04 0.01)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( via78       	m7      m8      	("v7" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.04 0.01)	(0.01 0.04)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( via67       	m6      m7      	("v6" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.01 0.04)	(0.04 0.01)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( via56       	m5      m6      	("v5" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.04 0.01)	(0.01 0.04)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( via45       	m4      m5      	("v4" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.01 0.04)	(0.04 0.01)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( via34       	m3      m4      	("v3" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.04 0.01)	(0.01 0.04)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( via23       	m2      m3      	("v2" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.01 0.04)	(0.04 0.01)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( via12       	m1      m2      	("v1" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.04 0.01)	(0.01 0.04)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )

  ( via89_swap       	m8      m9      	("v8" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.04 0.01)	(0.01 0.04)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( via78_swap       	m7      m8      	("v7" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.01 0.04)	(0.04 0.01)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )

  
  ( via67_swap       	m6      m7      	("v6" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.04 0.01)	(0.01 0.04)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( via56_swap       	m5      m6      	("v5" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.01 0.04)	(0.04 0.01)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )

  ( via45_swap       	m4      m5      	("v4" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.04 0.01)	(0.01 0.04)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( via34_swap       	m3      m4      	("v3" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.01 0.04)	(0.04 0.01)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( via23_swap       	m2      m3      	("v2" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.04 0.01)	(0.01 0.04)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( via12_swap       	m1      m2      	("v1" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.01 0.04)	(0.04 0.01)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )

  ( diffCont    	diff    m1      	("cont" 0.09 0.09)
     (1 1 (0.1 0.1))
     (0.05 0.05)	(0.04 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )

  ( polyCont    	poly    m1      	("cont" 0.09 0.09)
     (1 1 (0.1 0.1))
     (0.05 0.07)	(0.04 0.005)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )

  ( pdiff  		diff    m1      	("cont" 0.09 0.09)
     (1 1 (0.1 0.1))
     (0.05 0.05)	(0.005 0.04)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     pplus        	(0.02 0.02)
  )

  ( ndiff  		diff    m1      	("cont" 0.09 0.09)
     (1 1 (0.1 0.1))
     (0.05 0.05)	(0.005 0.04)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     nplus        	(0.02 0.02)
  )
  ( diffWellCont	diff    m1      	("cont" 0.09 0.09)
     (1 1 (0.1 0.1))
     (0.05 0.05)	(0.005 0.04)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
     nplus        	(0.02 0.02)	nwell		(0.275 0.24) 
  )


; Line vias definition
  ( via89Line       	m8      m9      	("v8" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.04 0.01)	(0.04 0.01)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( via78Line       	m7      m8      	("v7" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.04 0.01)	(0.04 0.01)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( via67Line       	m6      m7      	("v6" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.04 0.01)	(0.04 0.01)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( via56Line       	m5      m6      	("v5" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.04 0.01)	(0.04 0.01)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( via45Line       	m4      m5      	("v4" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.04 0.01)	(0.04 0.01)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( via34Line       	m3      m4      	("v3" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.04 0.01)	(0.04 0.01)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( via23Line       	m2      m3      	("v2" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.04 0.01)	(0.04 0.01)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )
  ( via12Line       	m1      m2      	("v1" 0.13 0.13 0.0016)
     (1 1 (0.15 0.15))
     (0.04 0.01)	(0.04 0.01)	(0.0 0.0)	(0.0 0.0)	(0.0 0.0)
  )

 ) ;standardViaDefs


 customViaDefs(
 ;( viaDefName libName cellName viewName layer1 layer2 resistancePerCut)
 ;( ---------- ------- -------- -------- ------ ------ ----------------)
  ( via12_cust reference90RF via12_cust layout m1 m2 1.0)
  ( via23_cust reference90RF via23_cust layout m2 m3 1.0)
  ( via34_cust reference90RF via34_cust layout m3 m4 1.0)
  ( via45_cust reference90RF via45_cust layout m4 m5 1.0)
  ( via56_cust reference90RF via56_cust layout m5 m6 1.0)
  ( via67_cust reference90RF via67_cust layout m6 m7 1.0)
  ( via78_cust reference90RF via78_cust layout m7 m8 1.0)
  ( via89_cust reference90RF via89_cust layout m8 m9 1.0)
  ( pdiff_cust reference90RF pdiff_cust layout diff m1 1.0)
  ( ndiff_cust reference90RF ndiff_cust layout diff m1 1.0)
  ( diff_cust reference90RF diff_cust layout diff m1 1.0)
  ( poly_cust reference90RF poly_cust layout poly m1 1.0)

  
 ) ;customViaDefs


) ;viaDefs



;********************************
; CONSTRAINT GROUPS
;********************************
constraintGroups(

 ;( group	[override] )
 ;( -----	---------- )
  ( "orionDefaultExtractorSetup"	nil
  ) ;orionDefaultExtractorSetup

 ;( group	[override] )
 ;( -----	---------- )
  ( "foundry"	nil


     designRules(

     ( minWidth                   "nwell"	0.55		-comment "Rule 7.1" "Rule 7.1: minWidth nwell 0.55um" )
     ( minSpacing                 "nwell"	0.55		-comment "Rule 7.2" "Rule 7.2: minSpacing nwell 0.55um" )
     ( minArea                    "nwell"	1.2  		-comment "Rule 7.3" "Rule 7.3: minArea nwell 1.2um^2")
     ( minEnclosedArea            "nwell"	1.2  		-comment "Rule 7.4" "Rule 7.4: minEnclosedArea nwell 1.2um^2")

     ( minWidth                   "diff"	0.09 		-comment "Rule 7.5" "Rule 7.5: minWidth diff 0.09um")
      ;  setting space diff - diff to 0.13um from 0.09. Enforce rule 1.11 instead of 7.6
     ( minSpacing                 "diff"	0.09 		-comment "Rule 7.6" "Rule 7.6: minSpacing diff 0.09um")
     ( minArea                    "diff"	0.05 		-comment "Rule 7.7" "Rule 7.7: minArea diff 0.05um^2")
     ( minEnclosedArea            "diff"	0.065 		-comment "Rule 7.8" "Rule 7.8: minEnclosedArea diff 0.065um^2")

     ( minWidth                   "poly"	0.09 		-comment "Rule 7.9" "Rule 7.9: minWidth poly 0.09um")
     ( minSpacing                 "poly"	0.09 		-comment "Rule 7.10" "Rule 7.10: minSpacing poly 0.09um")
     ( minArea                    "poly"	0.05 		-comment "Rule 7.11" "Rule 7.11: minArea poly 0.05um^2")
     ( minEnclosedArea            "poly"	0.05 		-comment "Rule 7.12" "Rule 7.12: minArea poly 0.09um^2")

     ( minWidth                   "pplus"  	0.2  		-comment "Rule 7.13" "Rule 7.13: minWidth pplus 0.2um")
     ( minSpacing                 "pplus"       0.1  		-comment "Rule 7.14" "Rule 7.14: minSpacing pplus 0.1um")
     ( minArea                    "pplus"       0.08 		-comment "Rule 7.15" "Rule 7.15: minArea pplus 0.08um^2")
     ( minEnclosedArea            "pplus"       0.11		-comment "Rule 7.16" "Rule 7.16: minEnclosedArea pplus 0.11um^2")

     ( minWidth                   "nplus"  	0.2  		-comment "Rule 7.17" "Rule 7.17: minWidth nplus 0.2um")
     ( minSpacing                 "nplus"       0.1  		-comment "Rule 7.18" "Rule 7.18: minSpacing nplus 0.1um")
     ( minArea                    "nplus"       0.08 		-comment "Rule 7.19" "Rule 7.19: minArea nplus 0.08um^2")
     ( minEnclosedArea            "nplus"       0.11		-comment "Rule 7.20" "Rule 7.20: minEnclosedArea nplus 0.11um^2")
   

     ( minWidth                   "rpoly"	0.34 		-comment "Rule 7.21" "Rule 7.21: minWidth rpoly 0.34um")
     ( minSpacing                 "rpoly"	0.34 		-comment "Rule 7.22" "Rule 7.22: minSpacing rpoly 0.34um")
     ( minArea                    "rpoly"	0.85 		-comment "Rule 7.23" "Rule 7.23: minArea rpoly 0.85um^2")
     ( minEnclosedArea            "rpoly"	0.85 		-comment "Rule 7.24" "Rule 7.24: minArea rpoly 0.85um^2")

     ( minWidth                   "cont"	0.09 		-comment "Rule 7.25" "Rule 7.25: minWidth cont 0.09um (square only allowed)")
     ( maxLength                  "cont"	0.09 		-comment "Rule 7.25a" "Rule 7.25a: maxLength cont 0.09um (square only allowed)")
     ( minSpacing                 "cont"	0.1  		-comment "Rule 7.26" "Rule 7.26: minSpacing cont 0.10um")

     ( minWidth                   "m1"	        0.1  		-comment "Rule 7.27" "Rule 7.27: minWidth m1 0.10um")
     ( maxWidth                   "m1"	        1000 		-comment "Rule 7.28" "Rule 7.28: maxWidth m1 1000.0um")
     ( minSpacing                 "m1"	        0.1  		-comment "Rule 7.29" "Rule 7.29: minSpacing m1 0.10um" )
     ( minArea                    "m1"	        0.04 		-comment "Rule 7.30" "Rule 7.30: minArea m1 0.04um^2")
     ( minEnclosedArea            "m1"	        0.30 		-comment "Rule 7.31" "Rule 7.31: minEnclosedArea m1 0.30um^2")
     
     ( minWidth                   "m2"	        0.15  		-comment "Rule 7.32" "Rule 7.32: minWidth m2 0.15um")
     ( maxWidth                   "m2"	        1000 		-comment "Rule 7.33" "Rule 7.33: maxWidth m2 1000.0um")
     ( minSpacing                 "m2"	        0.15  		-comment "Rule 7.34" "Rule 7.34: minSpacing m2 0.15um")
     ( minArea                    "m2"	        0.06 		-comment "Rule 7.35" "Rule 7.35: minArea m2 0.06um^2")
     ( minEnclosedArea            "m2"	        0.30 		-comment "Rule 7.36" "Rule 7.36: minEnclosedArea m2 0.30um^2")

     ( minWidth                   "m3"	        0.15  		-comment "Rule 7.37" "Rule 7.37: minWidth m3 0.15um")
     ( maxWidth                   "m3"	        1000 		-comment "Rule 7.38" "Rule 7.38: maxWidth m3 1000.0um")
     ( minSpacing                 "m3"	        0.15  		-comment "Rule 7.39" "Rule 7.39: minSpacing m3 0.15um")
     ( minArea                    "m3"	        0.06 		-comment "Rule 7.40" "Rule 7.40: minArea m3 0.06um^2")
     ( minEnclosedArea            "m3"	        0.30 		-comment "Rule 7.41" "Rule 7.41: minEnclosedArea m3 0.30um^2")


     ( minWidth                   "m4"	        0.15  		-comment "Rule 7.42" "Rule 7.42: minWidth m4 0.15um")
     ( maxWidth                   "m4"	        1000 		-comment "Rule 7.43" "Rule 7.43: maxWidth m4 1000.0um")
     ( minSpacing                 "m4"	        0.15  		-comment "Rule 7.44" "Rule 7.44: minSpacing m4 0.15um")
     ( minArea                    "m4"	        0.06 		-comment "Rule 7.45" "Rule 7.45: minArea m4 0.06um^2")
     ( minEnclosedArea            "m4"	        0.30 		-comment "Rule 7.46" "Rule 7.46: minEnclosedArea m4 0.30um^2")

     ( minWidth                   "m5"	        0.15  		-comment "Rule 7.xx" "Rule 7.xx: minWidth m5 0.15um")
     ( maxWidth                   "m5"	        1000 		-comment "Rule 7.xx" "Rule 7.xx: maxWidth m5 1000.0um")
     ( minSpacing                 "m5"	        0.15  		-comment "Rule 7.xx" "Rule 7.xx: minSpacing m5 0.15um")
     ( minArea                    "m5"	        0.06 		-comment "Rule 7.xx" "Rule 7.xx: minArea m5 0.06um^2")
     ( minEnclosedArea            "m5"	        0.30 		-comment "Rule 7.xx" "Rule 7.xx: minEnclosedArea m5 0.30um^2")

     ( minWidth                   "m6"	        0.15  		-comment "Rule 7.xx" "Rule 7.xx: minWidth m6 0.15um")
     ( maxWidth                   "m6"	        1000 		-comment "Rule 7.xx" "Rule 7.xx: maxWidth m6 1000.0um")
     ( minSpacing                 "m6"	        0.15  		-comment "Rule 7.xx" "Rule 7.xx: minSpacing m6 0.15um")
     ( minArea                    "m6"	        0.06 		-comment "Rule 7.xx" "Rule 7.xx: minArea m6 0.06um^2")
     ( minEnclosedArea            "m6"	        0.30 		-comment "Rule 7.xx" "Rule 7.xx: minEnclosedArea m6 0.30um^2")

     ( minWidth                   "m7"	        0.15  		-comment "Rule 7.xx" "Rule 7.xx: minWidth m7 0.15um")
     ( maxWidth                   "m7"	        1000 		-comment "Rule 7.xx" "Rule 7.xx: maxWidth m7 1000.0um")
     ( minSpacing                 "m7"	        0.15  		-comment "Rule 7.xx" "Rule 7.xx: minSpacing m7 0.15um")
     ( minArea                    "m7"	        0.06 		-comment "Rule 7.xx" "Rule 7.xx: minArea m7 0.06um^2")
     ( minEnclosedArea            "m7"	        0.30 		-comment "Rule 7.xx" "Rule 7.xx: minEnclosedArea m7 0.30um^2")

     ( minWidth                   "m8"	        0.15  		-comment "Rule 7.xx" "Rule 7.xx: minWidth m8 0.15um")
     ( maxWidth                   "m8"	        1000 		-comment "Rule 7.xx" "Rule 7.xx: maxWidth m8 1000.0um")
     ( minSpacing                 "m8"	        0.15  		-comment "Rule 7.xx" "Rule 7.xx: minSpacing m8 0.15um")
     ( minArea                    "m8"	        0.06 		-comment "Rule 7.xx" "Rule 7.xx: minArea m8 0.06um^2")
     ( minEnclosedArea            "m8"	        0.30 		-comment "Rule 7.xx" "Rule 7.xx: minEnclosedArea m8 0.30um^2")

     ( minWidth                   "m9"	        0.15  		-comment "Rule 7.xx" "Rule 7.xx: minWidth m9 0.15um")
     ( maxWidth                   "m9"	        1000 		-comment "Rule 7.xx" "Rule 7.xx: maxWidth m9 1000.0um")
     ( minSpacing                 "m9"	        0.15  		-comment "Rule 7.xx" "Rule 7.xx: minSpacing m9 0.15um")
     ( minArea                    "m9"	        0.06 		-comment "Rule 7.xx" "Rule 7.xx: minArea m9 0.06um^2")
     ( minEnclosedArea            "m9"	        0.30 		-comment "Rule 7.xx" "Rule 7.xx: minEnclosedArea m9 0.30um^2")

     ( minWidth                   "v1"		0.13 		-comment "Rule 7.47" "Rule 7.47: minWidth v1 0.13um")
     ( maxLength                  "v1"		0.13 		-comment "Rule 7.47" "Rule 7.47: maxLength v1 0.13um")
     ( minSpacing                 "v1"		0.15 		-comment "Rule 7.48" "Rule 7.48: minSpacing v1 0.15um")
     
     ( minWidth                   "v2"		0.13 		-comment "Rule 7.49" "Rule 7.47: minWidth v2 0.13um")
     ( maxLength                  "v2"		0.13 		-comment "Rule 7.49" "Rule 7.47: maxLength v2 0.13um")
     ( minSpacing                 "v2"		0.15 		-comment "Rule 7.50" "Rule 7.48: minSpacing v2 0.15um")

     ( minWidth                   "v3"		0.13 		-comment "Rule 7.51" "Rule 7.47: minWidth v3 0.13um")
     ( maxLength                  "v3"		0.13 		-comment "Rule 7.51" "Rule 7.47: maxLength v3 0.13um")
     ( minSpacing                 "v3"		0.15 		-comment "Rule 7.52" "Rule 7.48: minSpacing v3 0.15um")

     ( minWidth                   "v4"		0.13 		-comment "Rule 7.xx" "Rule 7.xx: minWidth v4 0.13um")
     ( maxLength                  "v4"		0.13 		-comment "Rule 7.xx" "Rule 7.xx: maxLength v4 0.13um")
     ( minSpacing                 "v4"		0.15 		-comment "Rule 7.xx" "Rule 7.xx: minSpacing v4 0.15um")

     ( minWidth                   "v5"		0.13 		-comment "Rule 7.xx" "Rule 7.xx: minWidth v5 0.13um")
     ( maxLength                  "v5"		0.13 		-comment "Rule 7.xx" "Rule 7.xx: maxLength v5 0.13um")
     ( minSpacing                 "v5"		0.15 		-comment "Rule 7.xx" "Rule 7.xx: minSpacing v5 0.15um")

     ( minWidth                   "v6"		0.13 		-comment "Rule 7.xx" "Rule 7.xx: minWidth v6 0.13um")
     ( maxLength                  "v6"		0.13 		-comment "Rule 7.xx" "Rule 7.xx: maxLength v6 0.13um")
     ( minSpacing                 "v6"		0.15 		-comment "Rule 7.xx" "Rule 7.xx: minSpacing v6 0.15um")

     ( minWidth                   "v7"		0.13 		-comment "Rule 7.xx" "Rule 7.xx: minWidth v7 0.13um")
     ( maxLength                  "v7"		0.13 		-comment "Rule 7.xx" "Rule 7.xx: maxLength v7 0.13um")
     ( minSpacing                 "v7"		0.15 		-comment "Rule 7.xx" "Rule 7.xx: minSpacing v7 0.15um")

     ( minWidth                   "v8"		0.13 		-comment "Rule 7.xx" "Rule 7.xx: minWidth v8 0.13um")
     ( maxLength                  "v8"		0.13 		-comment "Rule 7.xx" "Rule 7.xx: maxLength v8 0.13um")
     ( minSpacing                 "v8"		0.15 		-comment "Rule 7.xx" "Rule 7.xx: minSpacing v8 0.15um")



     ( minDualExtension		  "poly" 	"cont"		0.050 0.07	-comment "Rule 7.53/98" "Rule 7.53/98: minDualExtension poly over cont 0.05um/0.07um" ) 
     ( minDualExtension           "m1" 		"cont"		0.005 0.04	-comment "Rule 7.54/71" "Rule 7.54/71: minDualExtension m1 over cont 0.005um/0.04um" )

; DRM states a minDualExtension of diff over cont but hercules only checks for 0.05um and design is 0.05um so changed rule for now.
;     ( minDualExtension           "diff"	"cont"		0.05 0.07	-comment "Rule 7.64/99" "Rule 7.64/99: minDualExtension diff over cont 0.05um/0.07um" )
     ( minExtension           	   "diff"	"cont"		0.05 		-comment "Rule 7.64" "Rule 7.64: minExtension diff over cont 0.05um" )

     ( minDualExtension           "m1" 		"v1"		0.01 0.04	-comment "Rule 7.72/73" "Rule 7.72/73: minDualExtension m1 over v1 0.01um/0.04um" )
     ( minDualExtension           "m2" 		"v1"		0.01 0.04	-comment "Rule 7.74/75" "Rule 7.74/75: minDualExtension m2 over v1 0.01um/0.04um" )

     ( minDualExtension           "m2" 		"v2"		0.01 0.04	-comment "Rule 7.76/77" "Rule 7.76/77: minDualExtension m2 over v2 0.01um/0.04um" )
     ( minDualExtension           "m3" 		"v2"		0.01 0.04	-comment "Rule 7.78/79" "Rule 7.77/78: minDualExtension m3 over v2 0.01um/0.04um" )

     ( minDualExtension           "m3" 		"v3"		0.01 0.04	-comment "Rule 7.80/81" "Rule 7.80/81: minDualExtension m3 over v3 0.01um/0.04um" )
     ( minDualExtension           "m4" 		"v3"		0.01 0.04	-comment "Rule 7.82/83" "Rule 7.82/83: minDualExtension m4 over v3 0.01um/0.04um" )

     ( minDualExtension           "m4" 		"v4"		0.01 0.04	-comment "Rule 7.xx/xx" "Rule 7.xx/xx: minDualExtension m4 over v4 0.01um/0.04um" )
     ( minDualExtension           "m5" 		"v4"		0.01 0.04	-comment "Rule 7.xx/xx" "Rule 7.xx/xx: minDualExtension m5 over v4 0.01um/0.04um" )

     ( minDualExtension           "m5" 		"v5"		0.01 0.04	-comment "Rule 7.xx/xx" "Rule 7.xx/xx: minDualExtension m5 over v5 0.01um/0.04um" )
     ( minDualExtension           "m6" 		"v5"		0.01 0.04	-comment "Rule 7.xx/xx" "Rule 7.xx/xx: minDualExtension m6 over v5 0.01um/0.04um" )

     ( minDualExtension           "m6" 		"v6"		0.01 0.04	-comment "Rule 7.xx/xx" "Rule 7.xx/xx: minDualExtension m6 over v6 0.01um/0.04um" )
     ( minDualExtension           "m7" 		"v6"		0.01 0.04	-comment "Rule 7.xx/xx" "Rule 7.xx/xx: minDualExtension m7 over v6 0.01um/0.04um" )

     ( minDualExtension           "m7" 		"v7"		0.01 0.04	-comment "Rule 7.xx/xx" "Rule 7.xx/xx: minDualExtension m7 over v7 0.01um/0.04um" )
     ( minDualExtension           "m8" 		"v7"		0.01 0.04	-comment "Rule 7.xx/xx" "Rule 7.xx/xx: minDualExtension m8 over v7 0.01um/0.04um" )

     ( minDualExtension           "m8" 		"v8"		0.01 0.04	-comment "Rule 7.xx/xx" "Rule 7.xx/xx: minDualExtension m8 over v8 0.01um/0.04um" )
     ( minDualExtension           "m9" 		"v8"		0.01 0.04	-comment "Rule 7.xx/xx" "Rule 7.xx/xx: minDualExtension m9 over v8 0.01um/0.04um" )

     ( minClearance               "nwell"	"diff"		0.22	-comment "Rule 7.55" "Rule 7.55: minClearance nwell to diff 0.22um")
     ( minExtension               "nwell"	"diff"		0.23 	-comment "Rule 7.56" "Rule 7.56: minExtension nwell over diff 0.23um" )
     ( minExtension 	          "rpoly"       "poly"		0.22 	-comment "Rule 7.57" "Rule 7.57: minExtension rpoly over poly 0.22um" )
     ( minClearance               "rpoly"	"cont"		0.22 	-comment "Rule 7.58" "Rule 7.58: minClearance rpoly to cont 0.22um")
     ( minClearance               "diff"	"poly"		0.045 	-comment "Rule 7.61" "Rule 7.61: minClearance poly to diff 0.045um")
     ( minExtension               "poly"	"diff"		0.13 	-comment "Rule 7.62" "Rule 7.62: minExtension poly over diff (endcap 0.12um" )
     ( minExtension               "diff"	"poly"		0.16 	-comment "Rule 7.621" "Rule7.621: minExtension diff over poly 0.16um" )
     ( minClearance               "cont"	"diff"		0.1  	-comment "Rule 7.63" "Rule 7.63: minClearance diff to cont 0.10um" ) 
     ( minClearance               "cont"	"poly"		0.08 	-comment "Rule 7.65" "Rule 7.65 : minClearance poly to cont 0.08um")
 
     ( minExtension               "pplus" 	"cont"		0.06 	-comment "Rule 7.67" "Rule 7.67: minExtension pplus over cont 0.06um" )
     ( minExtension               "nplus" 	"cont"	 	0.06 	-comment "Rule 7.68" "Rule 7.68: minExtension nplus over cont 0.06um" )

     ( minClearance               "rpoly"	"poly"		0.22 	-comment "Rule 7.84" "Rule 7.84: minClearance rpoly to poly 0.22um" )
     ( minExtension 	          "poly"        "rpoly"		0.22 	-comment "Rule 7.85" "Rule 7.85: minExtension poly over rpoly 0.22um" )
     ( minClearance               "rpoly"	"cont"		0.22 	-comment "Rule 7.86" "Rule 7.86: minClearance rpoly to cont 0.22um" )
     ( minClearance               "rpoly"	"diff"		0.22 	-comment "Rule 7.87" "Rule 7.87: minClearance rpoly to cont 0.22um" )


;     ( minClearance               "pplus"	"diff"		0.13 	-comment "Rule 7.89." "Rule 7.89: minClearance pplus to diff 0.13um" )
;     ( minExtension	          "pplus"       "diff"		0.13 	-comment "Rule 7.90" "Rule 7.90 : minExtension pplus over diff 0.13um")

;     ( minClearance               "nplus"	"diff"		0.13 	-comment "Rule 7.91." "Rule 7.91: minClearance nplus to diff 0.13um" )
;     ( minExtension              "nplus"       "diff"		0.13 	-comment "Rule 7.92" "Rule 7.92 : minExtension nplus over diff 0.13um")

     ( minExtension               "cont"	"diff"		0.06 	-comment "Rule 7.95" "Rule 7.95: minClearance cont to diff 0.06um")

     ( minLargeViaArraySpacing 	  "v1" 				0 ((2 0.170)) 	-comment "7.96" "7.96: minLargeViaArraySpacing if v1 array size =>2 (0.17um)" )
     ( minLargeViaArraySpacing 	  "v2" 				0 ((2 0.170)) 	-comment "7.96" "7.96: minLargeViaArraySpacing if v2 array size =>2 (0.17um)" )
     ( minLargeViaArraySpacing 	  "v3" 				0 ((2 0.170)) 	-comment "7.96" "7.96: minLargeViaArraySpacing if v3 array size =>2 (0.17um)" )
     ( minLargeViaArraySpacing 	  "v4" 				0 ((2 0.170)) 	-comment "7.96" "7.96: minLargeViaArraySpacing if v4 array size =>2 (0.17um)" )
     ( minLargeViaArraySpacing 	  "v5" 				0 ((2 0.170)) 	-comment "7.96" "7.96: minLargeViaArraySpacing if v5 array size =>2 (0.17um)" )
     ( minLargeViaArraySpacing 	  "v6" 				0 ((2 0.170)) 	-comment "7.96" "7.96: minLargeViaArraySpacing if v6 array size =>2 (0.17um)" )
     ( minLargeViaArraySpacing 	  "v7" 				0 ((2 0.170)) 	-comment "7.96" "7.96: minLargeViaArraySpacing if v7 array size =>2 (0.17um)" )
     ( minLargeViaArraySpacing 	  "v8" 				0 ((2 0.170)) 	-comment "7.96" "7.96: minLargeViaArraySpacing if v8 array size =>2 (0.17um)" )
     ( minLargeViaArraySpacing 	  "cont" 			0 ((2 0.150)) 	-comment "7.97" "7.97: minLargeViaArraySpacing if CO array size =>2 (0.15um)" )

     ( minWidth                   "mtcap"  	1.00 		-comment "Rule 4.1" "Rule 4.1: minWidth mtcap 1.00um")
     ( minWidth                   "dnw"		2.8 		-comment "Rule 8.1" "Rule 8.1: minWidth dnw 2.8um")
     ( minSpacing                 "dnw"		4.4 		-comment "Rule 8.2" "Rule 8.2: minSpacing dnw 4.4um")

     ( minClearance               "nat"		"diff"		0.20	-comment "Rule 1.18" "Rule 1.18: minClearance nat to diff  0.20um") 
     ( minClearance               "nplus"	"pplus"		0.00 	-comment "Rule 7.69" "Rule 7.69: minClearance pplus to nplus 0.0um")	
     ( minExtension               "nwell"	"diff"		0.23 	-comment "Rule 3.18/19" "Rule 3.18/19: minExtension nwell over diff 0.23um" )
     ( minExtension               "rmarker"	"poly"		0.22 	-comment "Rule 2.128" "Rule 2.128: minExtension rmarker over poly 0.22um" )
     ( minExtension               "diff25"	"diff"		0.3  	-comment "Rule 1.10" "Rule 1.10: minExtension diff25 over diff 0.30um" )
     ( minExtension               "diff18"	"diff"		0.3  	-comment "Rule 1.187" "Rule 1.187: minExtension diff18 over diff 0.30um" )
     ( minExtension               "diff33"	"diff"		0.3  	-comment "Rule 1.177" "Rule 1.188: minExtension diff33 over diff 0.30um" )
     

; Design rules I have not found in DRM yet.

     ( minExtension               "nwdmy"	"nwell"		0.2  	-comment "Rule ?1" "Rule ?1:minExtension nwdmy over nwell 0.20um" )
;     ( minExtension               "nwell"	"pplus"		0.0  	-comment "Rule ?2" "Rule ?2: minExtension nwell over pplus" )
     ( minExtension               "nat"	        "diff"		0.28 	-comment "Rule ?3" "Rule ?3: minExtension nta over diff" )
     ( minExtension               "mtcap" 	"v3"		0.24 	-comment "Rule ?4" "Rule ?4: minExtension mtcap over v3" )
     ( minExtension               "mtcap"	"m3"		0.3  	-comment "Rule ?5" "Rule ?5: minExtension mtcap over M3" )
     ( minOverlap                 "nwell"	"rpoly"		0.50		-comment "Rule ?6" "Rule ?6: minOverlap nwell over rpoly")	
;     ( minOverlap                 "pplus"	"poly"		0.18		-comment "Rule ?8" "Rule ?8: minOverlap pplus over poly")
;     ( minOverlap                 "nplus"	"poly"		0.18		-comment "Rule ?9" "Rule ?9: minOverlap nplus over poly")
     ( minOverlap                 "nwell"	"dnw"		0.8 		-comment "Rule ?10" "Rule ?10: minOverlap nwell over dnw")
     ( minOverlap                 "pplus"	"rpoly"		0.18		-comment "Rule ?11" "Rule ?11: minOverlap pplus over rpoly")
     ( minOverlap                 "nplus"	"rpoly"		0.18		-comment "Rule ?12" "Rule ?12: minOverlap nplus over rpoly ")


  

    ) ;designRules

    electrical(
    ;( constraint		layer1		[layer2]	value  )
    ;( ----------		------		--------	-----  )
     ( contactRes                 "nplus" 	0.363776)
     ( contactRes                 "pplus" 	0.367872)
     ( contactRes                 "poly" 	0.28416)
     ( contactRes                 "v1"   	1)
     ( contactRes                 "v2"  	1)
     ( contactRes                 "v3"  	1)
     ( contactRes                 "v4"  	1)
     ( contactRes                 "v5"  	1)
     ( contactRes                 "v6"  	1)
     ( contactRes                 "v7"  	1)
     ( contactRes                 "v8"  	1)
    ) ;electrical

    orderedElectrical(
    ;( constraint		layer1		layer2		value  )
    ;( ----------		------		------		------  )
     ( areaCap                    "m1" 	 	"diff"		3.83e-05)
     ( areaCap                    "m1" 	 	"poly"		4.97e-05)
     ( areaCap                    "m2" 	 	"diff"		1.34e-05)
     ( areaCap                    "m2" 	 	"poly"		1.56e-05)
     ( areaCap                    "m2" 	 	"m1"		3.11e-05)
     ( areaCap                    "m3" 	 	"diff"		7.99e-06)
     ( areaCap                    "m3" 	 	"poly"		0.77e-05)
     ( areaCap                    "m3" 	 	"m1"		1.17e-05)
     ( areaCap                    "m3" 	 	"m2"		3.67e-05)
     ( areaCap                    "m4" 	 	"diff"		5.81e-06)
     ( areaCap                    "m4" 	 	"poly"		6.1e-06)
     ( areaCap                    "m4" 	 	"m1"		7.91e-06)
     ( areaCap                    "m4" 	 	"m2"		1.16e-05)
     ( areaCap                    "m4" 	 	"m3"		2.94e-05)
     ( edgeCapacitance            "m1" 	 	"diff"		4.448e-11)
     ( edgeCapacitance            "m2" 	 	"diff"		2.188e-11)
     ( edgeCapacitance            "m2" 	 	"poly"		2.271e-11)
     ( edgeCapacitance            "m2" 	 	"m1"		4.156e-11)
     ( edgeCapacitance            "m3" 	 	"diff"		1.432e-11)
     ( edgeCapacitance            "m3" 	 	"poly"		1.456e-11)
     ( edgeCapacitance            "m3" 	 	"m1"		2.34e-11)
     ( edgeCapacitance            "m3" 	 	"m2"		3.862e-11)
     ( edgeCapacitance            "m4" 	 	"diff"		1.278e-11)
     ( edgeCapacitance            "m4" 	 	"poly"		1.409e-11)
     ( edgeCapacitance            "m4" 	 	"m1"		1.642e-11)
     ( edgeCapacitance            "m4" 	 	"m2"		2.473e-11)
     ( edgeCapacitance            "m4" 	 	"m3"		4.116e-11)
     ( sheetRes                   "nwell" 	"diff"		472)
     ( contactRes                 "poly" 	"nplus"		0.31454)
     ( contactRes                 "poly" 	"pplus"		0.32416)
    ) ;orderedElectrical    

    interconnect(
     ( validRoutingLayers   ( v8  v7  v6  v5  v4  v3  v2  v1  m9  m8  m7  m6  m5 m4  m3  m2  m1  cont  poly  diff25  diff18 diff33  diff ) )
    ) ;interconnect

  ) ;foundry

  ( "LEFDefaultRouteSpec"   nil
     ( minWidth         		cont            	 0.09 )
     ( horizontalRouteGridPitch 	m1              	 0.2 )
     ( verticalRouteGridPitch 		m1              	 0.2 )
     ( horizontalRouteGridOffset 	m1              	 0.1 )
     ( verticalRouteGridOffset 		m1              	 0.1 )
     ( minWidth         		m1              	 0.1 )
     ( minWireExtension 		m1              	 0.105 )
     ( minWidth         		v1              	 0.13 )
     
     ( horizontalRouteGridPitch 	m2              	 0.3 )
     ( verticalRouteGridPitch 		m2              	 0.3 )
     ( horizontalRouteGridOffset 	m2              	 0.15 )
     ( verticalRouteGridOffset 		m2              	 0.15 )
     ( minWidth         		m2              	 0.15 )
     ( minWireExtension 		m2              	 0.105 )
     ( minWidth         		v2              	 0.13 )
     
     ( horizontalRouteGridPitch 	m3              	 0.3 )
     ( verticalRouteGridPitch 		m3              	 0.3 )
     ( horizontalRouteGridOffset 	m3              	 0.15 )
     ( verticalRouteGridOffset 		m3              	 0.15 )
     ( minWidth         		m3              	 0.15 )
     ( minWireExtension 		m3              	 0.105 )
     ( minWidth         		v3              	 0.13 )

     ( horizontalRouteGridPitch 	m4              	 0.3 )
     ( verticalRouteGridPitch 		m4              	 0.3 )
     ( horizontalRouteGridOffset 	m4              	 0.15 )
     ( verticalRouteGridOffset 		m4              	 0.15 )
     ( minWidth         		m4              	 0.15 )
     ( minWireExtension 		m4              	 0.105 )
     ( minWidth         		v4              	 0.13 )

     ( horizontalRouteGridPitch 	m5              	 0.3 )
     ( verticalRouteGridPitch 		m5              	 0.3 )
     ( horizontalRouteGridOffset 	m5              	 0.15 )
     ( verticalRouteGridOffset 		m5              	 0.15 )
     ( minWidth         		m5              	 0.15 )
     ( minWireExtension 		m5              	 0.105 )
     ( minWidth         		v5              	 0.13 )

     ( horizontalRouteGridPitch 	m6              	 0.3 )
     ( verticalRouteGridPitch 		m6              	 0.3 )
     ( horizontalRouteGridOffset 	m6              	 0.15 )
     ( verticalRouteGridOffset 		m6              	 0.15 )
     ( minWidth         		m6              	 0.15 )
     ( minWireExtension 		m6              	 0.105 )
     ( minWidth         		v6              	 0.13 )

     ( horizontalRouteGridPitch 	m7              	 0.3 )
     ( verticalRouteGridPitch 		m7              	 0.3 )
     ( horizontalRouteGridOffset 	m7              	 0.15 )
     ( verticalRouteGridOffset 		m7              	 0.15 )
     ( minWidth         		m7              	 0.15 )
     ( minWireExtension 		m7              	 0.105 )
     ( minWidth         		v7              	 0.13 )

     ( horizontalRouteGridPitch 	m8              	 0.3 )
     ( verticalRouteGridPitch 		m8              	 0.3 )
     ( horizontalRouteGridOffset 	m8              	 0.15 )
     ( verticalRouteGridOffset 		m8              	 0.15 )
     ( minWidth         		m8              	 0.15 )
     ( minWireExtension 		m8              	 0.105 )
     ( minWidth         		v8              	 0.13 )

     
     ( horizontalRouteGridPitch 	m9              	 0.3 )
     ( verticalRouteGridPitch 		m9              	 0.3 )
     ( horizontalRouteGridOffset 	m9              	 0.15 )
     ( verticalRouteGridOffset 		m9              	 0.15 )
     ( minWidth         		m9              	 0.15 )
     ( minWireExtension 		m9              	 0.105 )
     ( validRoutingLayers 	 (m1   m2   m3   m4  m5  m6  m7  m8  m9)
      )
     ( validRoutingVias 	 (via12 via23 via34 via45 via56 via67 via78 via89 polyCont diffCont via12_swap via23_swap via34_swap via45_swap via56_swap via67_swap via78_swap via89_swap )
      )
  );LEFDefaultRouteSpec


) ;constraintGroups


;********************************
; DEVICES
;********************************
devices(
tcCreateCDSDeviceClass()
) ;devices


;********************************
; LE RULES
;********************************
leRules(

 leLswLayers(
 ;( layer               purpose         )
 ;( -----               -------         )
 ) ;leLswLayers

) ;leRules

